name: Build and push devcontainer

on:
  push:
    branches:
      - main
env:
  REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
          contents: read
          packages: write
          attestations: write
          id-token: write
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Set up QEMU for multi-architecture builds
        uses: docker/setup-qemu-action@v3
      - name: Setup Docker buildx for multi-architecture builds
        uses: docker/setup-buildx-action@v3
        with:
          use: true
          platforms: linux/arm64
      - name: Github container registry login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build dev container multi image
        uses: devcontainers/ci@v0.3
        with:
          imageName: ${{ env.REGISTRY }}/${{ github.repository }}
          cacheFrom: ${{ env.REGISTRY }}/${{ github.repository }}
          push: always
          platform: linux/arm64
